### ISSUE TITLE
Seems like it is not supporting ING anymore.

### ISSUE THREAD

**Issue by ferryrs** [bank2ynab/bank2ynab#408]
Hi, I have been using the Master branch for a while now without any problems, using the NL ING Checking 2020 format for my situation. I think something has changed, because it is not working anymore.

When I try using the 'Master' branch I get the following error:

```
Parsing input file:  /Users/ferryras/Downloads/NLxxINGBxxxxxxxxxx_10-12-2021_30-12-2021.csv (format: NL ING Checking 2020)
INFO: Using encoding ascii with confidence 1.0
INFO: Using encoding ascii with confidence 1.0
Traceback (most recent call last):
  File "./__main__.py", line 19, in <module>
    b2y.run()
  File "/Applications/Bank2YNAB/bank2ynab-master/bank2ynab/bank_process.py", line 382, in run
    output = bank.read_data(src_file)
  File "/Applications/Bank2YNAB/bank2ynab-master/bank2ynab/bank_process.py", line 126, in read_data
    row = self._cd_flag_process(row, cd_flags)
  File "/Applications/Bank2YNAB/bank2ynab-master/bank2ynab/bank_process.py", line 305, in _cd_flag_process
    if row[indicator_col] == outflow_flag:
IndexError: list index out of range
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

Therefor I decided to download the latest version, to see if this is been updated. Now, when I use the Developer-branch I get the following error:

```
Traceback (most recent call last):
  File "./__main__.py", line 18, in <module>
    b2y = Bank2Ynab(config)
  File "/Applications/Bank2YNAB/bank2ynab-develop/bank2ynab/bank_process.py", line 361, in __init__
    bank_object = build_bank(bank_config)
  File "/Applications/Bank2YNAB/bank2ynab-develop/bank2ynab/bank_process.py", line 337, in build_bank
    p_mod = importlib.import_module("plugins.{}".format(plugin_module))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Applications/Bank2YNAB/bank2ynab-develop/bank2ynab/plugins/pdf_converter.py", line 1, in <module>
    import tabula
ModuleNotFoundError: No module named 'tabula'
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

Please advice.

**Comment by nocalla** [comment]
The Tabula error is something I caused yesterday while attempting to add PDF support. I'll fix that immediately and hopefully develop will work for you then. Otherwise, it's possible that ING has updated their bank format.

**Comment by nocalla** [comment]
The commit auto-closed the issue, but let me know if `develop` is still not working.

**Comment by ferryrs** [comment]
Now it returns a  'plugins.pdf_converter' error.

```
Traceback (most recent call last):
  File "./__main__.py", line 18, in <module>
    b2y = Bank2Ynab(config)
  File "/Applications/Bank2YNAB/bank2ynab-develop/bank2ynab/bank_process.py", line 361, in __init__
    bank_object = build_bank(bank_config)
  File "/Applications/Bank2YNAB/bank2ynab-develop/bank2ynab/bank_process.py", line 337, in build_bank
    p_mod = importlib.import_module("plugins.{}".format(plugin_module))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'plugins.pdf_converter'
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by nocalla** [comment]
Ok, hopefully the PDF stuff should be fixed now. That's something that snuck in from another in-progress branch.

**Comment by ferryrs** [comment]
Problem solved.

**Comment by nocalla** [comment]
Great, thanks for flagging the PDF issue though!
